#!/usr/bin/env python3
"""
Codex20 OpenRouter - Setup Wizard
Fase di installazione interattiva per prima configurazione
"""

import os
import sys
import json
import secrets
import hashlib
import subprocess
from pathlib import Path
from datetime import datetime

# Colori terminal
class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    END = '\033[0m'
    BOLD = '\033[1m'

def print_banner():
    print(f"""
{Colors.HEADER}
╔══════════════════════════════════════════════════════════╗
║                 🎲 Codex20 Setup Wizard                  ║
║         Installazione interattiva per GitHub             ║
╚══════════════════════════════════════════════════════════╝
{Colors.END}
""")

def get_input(prompt, default="", password=False):
    """Get input from user"""
    if default:
        prompt += f" [{default}]"
    prompt += ": "
    
    if password:
        import getpass
        value = getpass.getpass(Colors.BLUE + prompt + Colors.END)
    else:
        value = input(Colors.BLUE + prompt + Colors.END).strip()
    
    return value if value else default

def generate_password_hash(password):
    """Generate SHA256 hash for password"""
    return hashlib.sha256(password.encode()).hexdigest()

def step_api_key():
    """Step 1: OpenRouter API Key"""
    print(f"\n{Colors.CYAN}╔═══ STEP 1/4 ═══{Colors.END}")
    print(f"{Colors.BOLD}API Key OpenRouter{Colors.END}")
    print(f"{Colors.WARNING}Obtén tu API key gratuita en:{Colors.END}")
    print(f"{Colors.GREEN}   https://openrouter.ai/keys{Colors.END}\n")
    
    api_key = get_input("API Key", password=True)
    
    if not api_key.startswith("sk-or-v1-"):
        print(f"{Colors.WARNING}⚠️  La chiave dovrebbe iniziare con 'sk-or-v1-'...{Colors.END}")
    
    return api_key

def step_models():
    """Step 2: Model Selection"""
    print(f"\n{Colors.CYAN}╔═══ STEP 2/4 ═══{Colors.END}")
    print(f"{Colors.BOLD}Selezione Modello AI{Colors.END}\n")
    
    models = [
        {"id": "1", "name": "google/gemma-4-31b-it:free", "desc": "Gemma 4 31B - Default"},
        {"id": "2", "name": "qwen/qwen3.5:free", "desc": "Qwen 3.5"},
        {"id": "3", "name": "meta-llama/llama-3.3-70b-instruct:free", "desc": "Llama 3.3 70B"},
        {"id": "4", "name": "nvidia/nemotron-3-ultra-550b-a55b:free", "desc": "Nemotron 3 550B"},
    ]
    
    print("Modelli disponibili:")
    for model in models:
        print(f"  {model['id']}. {model['name']}")
    
    choice = get_input("Seleziona modello [1]", default="1")
    
    if choice in [m["id"] for m in models]:
        selected = next(m for m in models if m["id"] == choice)
        return selected["name"], True
    else:
        print(f"{Colors.WARNING}Scelta non valida, uso default: gemma-4{Colors.END}")
        return models[0]["name"], False

def step_admin_user():
    """Step 3: Admin User Creation"""
    print(f"\n{Colors.CYAN}╔═══ STEP 3/4 ═══{Colors.END}")
    print(f"{Colors.BOLD}Creazione Utente Admin{Colors.END}\n")
    
    username = get_input("Username admin", default="admin")
    password = get_input("Password", password=True)
    
    if not password:
        print(f"{Colors.FAIL}❌ Password non può essere vuota!{Colors.END}")
        sys.exit(1)
    
    return username, password

def step_backup_model():
    """Step 4: Backup Model"""
    print(f"\n{Colors.CYAN}╔═══ STEP 4/4 ═══{Colors.END}")
    print(f"{Colors.BOLD}Modello di Backup{Colors.END}")
    print(f"{Colors.WARNING}Usato quando il modello principale è rate-limited{Colors.END}\n")
    
    backup_models = [
        {"id": "1", "name": "nvidia/nemotron-3-ultra-550b-a55b:free"},
        {"id": "2", "name": "qwen/qwen3.5:free"},
        {"id": "3", "name": "google/gemma-4-31b-it:free"},
    ]
    
    print("Backup modelli:")
    for model in backup_models:
        print(f"  {model['id']}. {model['name']}")
    
    choice = get_input("Seleziona backup [1]", default="1")
    
    if choice in [m["id"] for m in backup_models]:
        selected = next(m for m in backup_models if m["id"] == choice)
        return selected["name"], True
    else:
        return backup_models[0]["name"], False

def generate_env_file(admin_user, admin_password, api_key, model, backup_model):
    """Generate .env file with all configurations"""
    jwt_secret = secrets.token_hex(32)
    password_hash = generate_password_hash(admin_password)
    
    env_content = f"""# Codex20 OpenRouter - Configuration
# Generated by Setup Wizard on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

# ============================================
# AI Configuration
# ============================================
OPENROUTER_API_KEY={api_key}
MODEL_NAME={model}
BACKUP_MODEL_NAME={backup_model}
OPENROUTER_BASE_URL=https://openrouter.ai/api/v1
OPENROUTER_MAX_RETRIES=3
OPENROUTER_DELAY=1.0
OPENROUTER_CACHE_TTL=120

# ============================================
# Security
# ============================================
ADMIN_USERNAME={admin_user}
ADMIN_PASSWORD_HASH={password_hash}
JWT_SECRET={jwt_secret}

# ============================================
# Server
# ============================================
WEB_PORT=8084
BOT_PORT=8085
LOG_LEVEL=INFO
DATABASE_URL=sqlite:///data/sessions.db
"""
    
    with open(".env", "w") as f:
        f.write(env_content)
    
    print(f"{Colors.GREEN}✅ File .env creato con successo!{Colors.END}")
    return True

def run_docker_compose():
    """Run docker-compose to build and start services"""
    print(f"\n{Colors.CYAN}╔═══ BUILD & START ═══{Colors.END}")
    print(f"{Colors.BOLD}Avvio servizio Codex20{Colors.END}\n")
    
    try:
        # Build image
        print(f"{Colors.BLUE}📦 Building Docker image...{Colors.END}")
        subprocess.run(["docker", "compose", "build"], check=True)
        
        # Start services
        print(f"{Colors.BLUE}🚀 Starting services...{Colors.END}")
        subprocess.run(["docker", "compose", "up", "-d"], check=True)
        
        print(f"\n{Colors.GREEN}╔═══ SETUP COMPLETO ═══{Colors.END}")
        print(f"{Colors.GREEN}{Colors.BOLD}🎉 Codex20 è pronto!{Colors.END}")
        print(f"\n{Colors.CYAN}Accedi all'interfaccia web:{Colors.END}")
        print(f"{Colors.GREEN}   http://localhost:8085{Colors.END}")
        print(f"{Colors.CYAN}Credenziali admin:{Colors.END}")
        print(f"{Colors.GREEN}   Username: admin{Colors.END}")
        print(f"{Colors.GREEN}   Password: <quella inserita>{Colors.END}")
        
        return True
        
    except subprocess.CalledProcessError as e:
        print(f"{Colors.FAIL}❌ Errore durante l'avvio: {e}{Colors.END}")
        print(f"\n{Colors.WARNING}Puoi avviare manualmente:{Colors.END}")
        print(f"  docker compose up -d")
        return False

def main():
    """Main setup flow"""
    print_banner()
    
    # Check if .env exists
    if os.path.exists(".env"):
        print(f"{Colors.WARNING}⚠️  File .env esiste già!{Colors.END}")
        choice = input(f"{Colors.BLUE}Riconfigurare? [y/N]: {Colors.END}").lower()
        if choice != 'y':
            print(f"{Colors.GREEN}Setup annullato.{Colors.END}")
            sys.exit(0)
    
    try:
        # Collect configurations
        api_key = step_api_key()
        model, _ = step_models()
        admin_user, admin_password = step_admin_user()
        backup_model, _ = step_backup_model()
        
        # Generate .env
        print(f"\n{Colors.BLUE}Generazione configurazione...{Colors.END}")
        generate_env_file(admin_user, admin_password, api_key, model, backup_model)
        
        # Run Docker
        run_docker_compose()
        
    except KeyboardInterrupt:
        print(f"\n{Colors.WARNING}Setup annullato dall'utente.{Colors.END}")
        sys.exit(0)
    except Exception as e:
        print(f"{Colors.FAIL}❌ Errore: {e}{Colors.END}")
        sys.exit(1)

if __name__ == "__main__":
    main()
